source: .
destination: ./_site
includes: ./_includes
baseurl: null

collections:
  projects:
    output: true

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

plugins:
  - jekyll-sitemap
