source: .
destination: ./_site
includes: ./_includes
baseurl: null
relative_url: "https://mmeendez8.github.io"

# collections:
#   holas:
#     output: true

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

plugins:
  - jekyll-sitemap
